apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  selector:
    matchLabels:
      app: accounts-service
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: app
          image: koko120/accounts-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts-service
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
